version: "3.7"

networks:
  reverse-proxy:
    external: true


services:
  goservice:
    build: .
    #command: sh -c "go run main.go" # useful while debugging
    # environment:
    #   - TRUSTED_PROXIES=${TRUSTED_PROXIES:-?.?.?.?/?}
    # ports:
    #   - "8080:80"
    working_dir: /go/src/app
    restart: always
    volumes:
      - .:/go/src/app
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.enable=true"
      - "traefik.port=${SSE_PORT}"
      - "traefik.backend=${COMPOSE_PROJECT_NAME}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:${SSE_URL}"
      - "traefik.frontend.whiteList.sourceRange=${WHITELIST}"
    networks:
      - reverse-proxy
